### ISSUE TITLE
Issue with `[:repl-options :init]` composability

### ISSUE THREAD

**Issue by gfredericks** [greglook/whidbey#21]
See https://github.com/technomancy/leiningen/issues/1997.

**Comment by greglook** [comment]
Hmm - I tried adding this, but I get the following exception when loading the REPL:

```
Exception in thread "main" java.lang.ClassNotFoundException: whidbey.repl, compiling:(/tmp/form-init7248396931002679838.clj:1:1052)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler$VectorExpr.parse(Compiler.java:3195)
        at clojure.lang.Compiler.analyze(Compiler.java:6526)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.eval(Compiler.java:6779)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.eval(Compiler.java:6771)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```
The same setup without a wrapping vector works fine however.

**Comment by johannesloetzsch** [comment]
> Hmm - I tried adding this, but I get the following exception when loading the REPL:
```
Exception in thread "main" java.lang.ClassNotFoundException: whidbey.repl, compiling:(/tmp/form-init7248396931002679838.clj:1:1052)
```

You need `(require '[whidbey.repl])` in the namespace defined in `project.clj` as `:repl-options {:init-ns …}`

Please check my [working example](https://github.com/johannesloetzsch/whidbey/tree/master/example)

**Comment by johannesloetzsch** [comment]
I just realized that https://github.com/greglook/whidbey/pull/28 fixes this too :)

**Comment by johannesloetzsch** [comment]
I think this Issue can be closed, since master now contains a working solution.

Feel free to try my example at https://github.com/greglook/whidbey/pull/29 and merge or ignore it as you prefere.

**Comment by gfredericks** [comment]
I don't have the bandwidth right now to verify that it's fixed, so I don't mind if the issue is closed.
