### ISSUE TITLE
Doesn't work with Clojure 1.8

### ISSUE THREAD

**Issue by pjlegato** [greglook/whidbey#24]
Whidbey crashes everything when loaded as a plugin in Clojure 1.8.

This is perhaps related to https://github.com/venantius/ultra/issues/47 and https://github.com/venantius/ultra/issues/59 .

```

Exception in thread "main" java.io.FileNotFoundException: Could not locate fipp/engine__init.class or fipp/engine.clj on classpath., compiling:(puget/printer.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at whidbey.repl$eval1529$loading__5569__auto____1530.invoke(repl.clj:1)
	at whidbey.repl$eval1529.invokeStatic(repl.clj:1)
	at whidbey.repl$eval1529.invoke(repl.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
```

**Comment by greglook** [comment]
Can you post the output of `lein deps :tree` in the project you're seeing this in? Whidbey definitely works with Clojure 1.8.0 - the error your seeing implies to me that the version of Clojure you're using doesn't recognize `.cljc` files, which Fipp was ported over to in order to support both clojure and clojurescript.

**Comment by greglook** [comment]
Happy to help if you have more info, but without that there's not much more I can do. Feel free to reopen.

**Comment by pjlegato** [comment]
Thanks for your offer. I'm slammed at the moment, but when I have some spare cycles I'll look into it more.

**Comment by Immortalin** [comment]
@greglook stacktrace:
```Clojure
Possibly confusing dependencies found:
[gui-diff "0.6.7"] -> [fipp "0.4.1"]
 overrides
[venantius/ultra "0.5.0"] -> [mvxcvi/whidbey "1.3.0"] -> [mvxcvi/puget "1.0.0"] -> [fipp "0.6.3"]
 and
[venantius/ultra "0.5.0"] -> [mvxcvi/puget "1.0.1"] -> [fipp "0.6.6"]

Consider using these exclusions:
[venantius/ultra "0.5.0" :exclusions [fipp]]
[venantius/ultra "0.5.0" :exclusions [fipp]]

 [alembic "0.3.2"]
   [lein-as-resource "2.5.0" :exclusions [[org.clojure/clojure]]]
   [org.flatland/classlojure "0.7.0" :exclusions [[org.clojure/clojure]]]
 [cider/cider-nrepl "0.14.0"]
   [org.tcrawley/dynapath "0.2.4" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [gui-diff "0.6.7"]
   [fipp "0.4.1"]
     [org.clojure/data.finger-tree "0.0.1"]
     [transduce "0.1.0"]
   [org.clojars.trptcolin/sjacket "0.1.4" :exclusions [[org.clojure/clojure]]]
     [net.cgrand/parsley "0.9.1"]
     [net.cgrand/regex "1.1.0"]
   [org.codehaus.jsr166-mirror/jsr166y "1.7.0"]
   [org.flatland/ordered "1.5.3"]
     [org.flatland/useful "0.9.0"]
 [instaparse "1.4.3"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.macro "0.1.2"]
 [org.clojure/tools.nrepl "0.2.12"]
 [refactor-nrepl "2.2.0"]
 [venantius/ultra "0.5.0"]
   [grimradical/clj-semver "0.3.0" :exclusions [[org.clojure/clojure]]]
   [io.aviso/pretty "0.1.30"]
   [mvxcvi/puget "1.0.1"]
     [mvxcvi/arrangement "1.1.0"]
   [mvxcvi/whidbey "1.3.0"]
     [org.clojure/data.codec "0.1.0"]
   [org.clojars.brenton/google-diff-match-patch "0.1"]
   [robert/hooke "1.3.0"]
   [venantius/glow "0.1.4" :exclusions [[hiccup] [garden]]]
     [clj-antlr "0.2.3"]
       [org.antlr/antlr4-runtime "4.5.3"]
       [org.antlr/antlr4 "4.5.3"]
```

**Comment by greglook** [comment]
@Immortalin this should be in a new issue, but that message `Possibly confusing dependencies found` is from Leiningen, not Whidbey. You have `:pedantic? :warn` or `:abort` in your project definition, and it's complaining that the dependency chain through `gui-diff` is overriding the `fipp` version ultimately pulled in by this plugin.
